export const RECIPES_COPY = {
  title: "Biblioteca",
  views: {
    recipes: "Recetas",
    collections: "Colecciones",
  },
  searchPlaceholder: "Buscar por nombre…",
  loading: "Cargando recetas…",
  loadError: "No pudimos cargar las recetas.",
  noResults: "Aún no hay recetas por aquí.",
  noResultsHint: "Prueba con otra búsqueda o ajusta los filtros.",
  collectionsLoading: "Cargando colecciones…",
  collectionsLoadError: "No pudimos cargar las colecciones.",
  collectionsEmpty: "Aún no tienes colecciones.",
  collectionsEmptyHint: "Desde desayunos rápidos hasta recetas de la abuela, crea colecciones a tu manera.",
  recipeCount: (count: number) =>
    count === 1 ? "1 receta" : `${count} recetas`,
  fab: {
    addRecipe: "Crear receta",
    addCollection: "Crear colección",
  },
  collectionDetail: {
    back: "Volver a biblioteca",
    loading: "Cargando colección…",
    loadError: "No pudimos cargar esta colección.",
    notFound: "No encontramos esta colección.",
  },
  recipeDetail: {
    back: "Volver a biblioteca",
    loading: "Cargando receta…",
    notFound: "No encontramos esta receta.",
    comingSoon: "El detalle completo estará disponible pronto.",
  },
  create: {
    title: "Nueva receta",
    save: "Guardar receta",
    back: "Volver",
    sections: {
      cover: "Foto",
      basic: "Información",
      ingredients: "Ingredientes",
      steps: "Pasos",
      tags: "Etiquetas",
    },
    cover: {
      add: "Añadir foto",
      change: "Cambiar",
      hint: "Opcional — puedes agregarla ahora o después",
    },
    fields: {
      titlePlaceholder: "Título de la receta",
      descriptionPlaceholder: "Descripción breve, opcional…",
      publicLabel: "Receta pública",
      publicHint: "Visible para otros usuarios",
    },
    ingredients: {
      add: "Añadir ingrediente",
      empty: "Agrega los ingredientes de esta receta.",
      namePlaceholder: "Nombre del ingrediente",
      quantityPlaceholder: "Cant.",
      unitSearchPlaceholder: "Buscar unidad…",
      unitPickerTitle: "Unidad de medida",
      remove: "Quitar ingrediente",
      loadUnitsError: "No pudimos cargar las unidades.",
    },
    steps: {
      add: "Añadir paso",
      empty: "Describe cómo se prepara esta receta.",
      descriptionPlaceholder: "Describe este paso…",
      durationPlaceholder: "Min",
      durationLabel: "Duración",
      remove: "Quitar paso",
      reorder: "Reordenar pasos",
    },
    tags: {
      loading: "Cargando etiquetas…",
      loadError: "No pudimos cargar las etiquetas.",
      add: "Agregar etiquetas",
      sheetTitle: "Clasifica tu receta",
      sheetDescription: "Elige una o varias etiquetas para tu receta.",
      searchPlaceholder: "Buscar etiqueta…",
      done: "Listo",
      createNew: "Nueva",
      createPlaceholder: "Nombre de la etiqueta",
      createNamed: (name: string) => `${name}`,
      emptySearch: "No encontramos esa etiqueta",
      remove: (name: string) => `Quitar etiqueta ${name}`,
      editName: "Editar nombre de etiqueta",
      saveEdit: "Guardar nombre",
      cancelEdit: "Cancelar edición",
      renameError: "No pudimos renombrar la etiqueta.",
      duplicateName: "Ya existe una etiqueta con ese nombre.",
      createError: "No pudimos crear la etiqueta. Intenta de nuevo.",
      clearAll: "Limpiar todo",
    },
    errors: {
      save: "No pudimos guardar la receta. Revisa los datos e intenta de nuevo.",
    },
  },
} as const;
