export const RECIPES_COPY = {
  title: "Biblioteca",
  views: {
    recipes: "Recetas",
    collections: "Colecciones",
  },
  searchPlaceholder: "Buscar por nombre…",
  loading: "Cargando recetas…",
  loadError: "No pudimos cargar las recetas.",
  noResults: "Aún no hay recetas por aquí.",
  noResultsHint: "Prueba con otra búsqueda o ajusta los filtros.",
  collectionsLoading: "Cargando colecciones…",
  collectionsLoadError: "No pudimos cargar las colecciones.",
  collectionsEmpty: "Aún no tienes colecciones.",
  collectionsEmptyHint: "Desde desayunos rápidos hasta recetas de la abuela, crea colecciones a tu manera.",
  recipeCount: (count: number) =>
    count === 1 ? "1 receta" : `${count} recetas`,
  fab: {
    addRecipe: "Crear receta",
    addCollection: "Crear colección",
    addRecipesToCollection: "Añadir recetas",
  },
  collections: {
    createTitle: "Nueva colección",
    editTitle: "Editar colección",
    nameLabel: "Nombre",
    namePlaceholder: "Ej. Desayunos rápidos",
    colorLabel: "Color",
    create: "Crear colección",
    save: "Guardar cambios",
    cancel: "Cancelar",
    delete: "Eliminar colección",
    deleteTitle: "Eliminar colección",
    deleteDescription:
      "Las recetas no se borran, solo dejan de estar en esta colección.",
    deleteConfirm: "Eliminar",
    createSuccess: "Colección creada",
    updateSuccess: "Colección actualizada",
    deleteSuccess: "Colección eliminada",
    saveError: "No pudimos guardar la colección. Intenta de nuevo.",
    deleteError: "No pudimos eliminar la colección. Intenta de nuevo.",
    addRecipesTitle: "Añadir recetas",
    addRecipesDescription: "Elige las recetas que quieres incluir.",
    addRecipesConfirm: (count: number) =>
      count === 1 ? "Añadir 1 receta" : `Añadir ${count} recetas`,
    addRecipesSuccess: "Recetas añadidas a la colección",
    addRecipesError: "No pudimos añadir las recetas. Intenta de nuevo.",
    addRecipesEmpty: "Selecciona al menos una receta.",
    clearSelection: "Limpiar selección",
    removeRecipe: "Quitar de la colección",
    removeRecipeSuccess: "Receta quitada de la colección",
    removeRecipeError: "No pudimos quitar la receta. Intenta de nuevo.",
    alreadyInCollection: "Ya está en la colección",
  },
  collectionDetail: {
    back: "Volver a biblioteca",
    loading: "Cargando colección…",
    loadError: "No pudimos cargar esta colección.",
    notFound: "No encontramos esta colección.",
    edit: "Editar colección",
    emptyTitle: "Esta colección está vacía",
    emptyHint: "Añade recetas para empezar a organizarlas aquí.",
  },
  recipeDetail: {
    back: "Volver a biblioteca",
    loading: "Cargando receta…",
    loadError: "No pudimos cargar esta receta.",
    notFound: "No encontramos esta receta.",
    sourceSuggested: "Sugerida por Namly",
    originSuggested: "Sugerida",
    originPublic: "Pública",
    originOwn: "Propia",
    tabs: {
      cook: "Cocinar",
      experience: "Tu experiencia",
    },
    sections: {
      ingredients: "Ingredientes",
      preparation: "Preparación",
      rating: "Tu valoración",
      opinion: "Tu opinión",
    },
    compatibilityWarning:
      "Esta receta contiene ingredientes que pueden no ser compatibles con tus preferencias.",
    ingredientsEmpty: "Esta receta aún no tiene ingredientes.",
    preparationEmpty: "Esta receta aún no tiene pasos de preparación.",
    ratingOf: (rating: number) => `${rating} de 5`,
    ratingClear: "Quitar valoración",
    opinionPlaceholder: "",
    opinionExamples:
      "¿Qué tal te fue con esta receta?",
    favoriteAdd: "Añadir a favoritas",
    favoriteRemove: "Quitar de favoritas",
    feedbackError: "No pudimos guardar tu valoración. Intenta de nuevo.",
    editRecipe: "Editar receta",
    deleteRecipe: "Eliminar receta",
    deleteRecipeTitle: "Eliminar receta",
    deleteRecipeDescription:
      "Esta acción no se puede deshacer. La receta dejará de estar en tu biblioteca.",
    deleteRecipeConfirm: "Eliminar",
    deleteRecipeCancel: "Cancelar",
    deleteRecipeSuccess: "Receta eliminada",
    deleteRecipeError: "No pudimos eliminar la receta. Intenta de nuevo.",
  },
  edit: {
    title: "Editar receta",
    save: "Guardar cambios",
    loadError: "No pudimos cargar esta receta.",
  },
  create: {
    title: "Nueva receta",
    save: "Guardar receta",
    back: "Volver",
    sections: {
      classification: "Clasifica tu receta",
    },
    tabs: {
      ingredients: "Ingredientes",
      preparation: "Preparación",
    },
    cover: {
      add: "Añadir foto",
      change: "Cambiar",
    },
    fields: {
      titlePlaceholder: "Título de la receta",
      descriptionLabel: "Descripción",
      descriptionOptional: "opcional",
      descriptionPlaceholder: "Una nota breve sobre la receta…",
      publicLabel: "Compartir con la comunidad",
      publicHint: "Otros usuarios podrán encontrar esta receta.",
    },
    ingredients: {
      add: "Añadir ingrediente",
      empty: "Empieza con el primer ingrediente.",
      namePlaceholder: "Ingrediente",
      quantityPlaceholder: "0",
      unitFallback: "unidad",
      unitSearchPlaceholder: "Buscar unidad…",
      unitPickerTitle: "Unidad de medida",
      remove: "Quitar ingrediente",
      reorder: "Reordenar ingredientes",
      loadUnitsError: "No pudimos cargar las unidades.",
    },
    steps: {
      add: "Añadir paso",
      empty: "Describe cómo se prepara.",
      descriptionPlaceholder: "Describe este paso…",
      durationPlaceholder: "5",
      durationLabel: "min",
      remove: "Quitar paso",
      reorder: "Reordenar pasos",
    },
    tags: {
      loading: "Cargando etiquetas…",
      loadError: "No pudimos cargar las etiquetas.",
      add: "Agregar etiquetas",
      sheetTitle: "Clasifica tu receta",
      sheetDescription: "Elige una o varias etiquetas para describirla.",
      classificationHint: "Elige una o varias etiquetas para describirla.",
      clear: "Limpiar",
      searchPlaceholder: "Buscar etiqueta…",
      done: "Listo",
      createNew: "Nueva",
      createPlaceholder: "Nombre de la etiqueta",
      createNamed: (name: string) => `${name}`,
      emptySearch: "No encontramos esa etiqueta",
      remove: (name: string) => `Quitar etiqueta ${name}`,
      editName: "Editar nombre de etiqueta",
      saveEdit: "Guardar nombre",
      cancelEdit: "Cancelar edición",
      renameError: "No pudimos renombrar la etiqueta.",
      duplicateName: "Ya existe una etiqueta con ese nombre.",
      createError: "No pudimos crear la etiqueta. Intenta de nuevo.",
      clearAll: "Limpiar todo",
    },
    errors: {
      save: "No pudimos guardar la receta. Revisa los datos e intenta de nuevo.",
      validation: "Revisa los campos marcados antes de guardar.",
    },
  },
} as const;
