export const REGISTER_MEAL_COPY = {
  title: "Registrar comida",
  save: "Guardar registro",
  back: "Volver",
  sections: {
    photo: "Foto",
    note: "Nota",
    mood: "¿Cómo te sentiste?",
    when: "Cuándo",
    plan: "¿Parte de tu plan?",
    mealType: "Tipo de comida",
    recipes: "Recetas",
    tags: "Etiquetas",
  },
  photo: {
    add: "Tomar foto",
    change: "Cambiar foto",
    emptyHint: "La foto es obligatoria para guardar el registro",
  },
  note: {
    placeholder: "Descripción opcional…",
  },
  when: {
    edit: "Editar",
  },
  plan: {
    matchTitle: "Coincide con tu plan de hoy",
    link: "Vincular",
    seeOthers: "Ver otros planes",
    linked: "Vinculado a tu plan",
    noMatch: "Sin coincidencia automática",
    searchPlan: "Buscar en tu plan",
    expressDetail: "Nota rápida",
  },
  recipes: {
    add: "Añadir receta",
    placeholder: "Nombre de la receta",
    remove: "Quitar",
  },
  tags: {
    browse: "Etiquetas",
    sheetTitle: "Etiquetas",
    sheetDescription: "Busca una etiqueta o crea una nueva para este registro.",
    searchPlaceholder: "Buscar etiqueta…",
    create: "Crear etiqueta",
    createNamed: (name: string) => `Crear "${name}"`,
    done: "Listo",
    clear: "Quitar todas",
    remove: (name: string) => `Quitar ${name}`,
    emptySearch: "No encontramos esa etiqueta",
    loading: "Cargando etiquetas…",
    loadError: "No pudimos cargar las etiquetas.",
  },
  errors: {
    load: "No pudimos abrir el registro. Intenta de nuevo.",
    save: "No pudimos guardar tu comida. Intenta de nuevo.",
    photoRequired: "Añade una foto antes de guardar.",
  },
} as const;
