export const PROFILE_COPY = {
  title: "Configuración",
  editTitle: "Editar perfil",
  back: "Volver",
  accountSection: "Cuenta",
  editProfile: {
    title: "Editar perfil",
    subtitle: "Nombre y foto",
  },
  signOut: {
    title: "Cerrar sesión",
    subtitle: "Salir de tu cuenta",
    confirming: "Cerrando sesión…",
  },
  loadError: "No pudimos cargar tu perfil. Intenta de nuevo.",
  saveError: "No pudimos guardar los cambios. Intenta de nuevo.",
  saveSuccess: "Perfil actualizado",
  avatarSection: "Foto de perfil",
  changePhoto: "Cambiar foto",
  removePhoto: "Eliminar",
  nameSection: "Nombre",
  displayNameLabel: "Nombre para mostrar",
  displayNamePlaceholder: "Tu nombre",
  linkedAccountSection: "Cuenta vinculada",
  saveChanges: "Guardar cambios",
  saving: "Guardando…",
  uploadError: "No pudimos subir la foto. Intenta de nuevo.",
  avatarAlt: "Foto de perfil",
} as const;
