export const MEAL_TYPES_COPY = {
  form: {
    viewAll: "Ver todos",
    info: {
      ariaLabel: "Más info sobre tipos de comida",
      title: "Tus tipos de comida más usados",
      description:
        "Mostramos los tipos de comida que más eliges al planear o registrar comidas.",
      bullets: [
        "¿No ves el que buscas? Toca Ver todos y elige otro — también puedes crear uno nuevo.",
        "Para editarlos o cambiar el orden, puedes hacerlo en Configuración → Tipos de comida.",
      ],
    },
  },
  selectSheet: {
    title: "Tus tipos de comida",
    subtitle: "Busca uno de la lista o crea uno nuevo.",
    searchPlaceholder: "Buscar tipo…",
    createNamed: (name: string) => `Crear "${name}"`,
    createNew: "Crear nuevo tipo",
    createPlaceholder: "Nombre del tipo",
    confirmCreate: "Crear tipo",
    emptySearch: "No hay tipos que coincidan.",
    settingsLink: "Configurar tipos en tu perfil",
    habitualBadge: "Habitual",
  },
  management: {
    title: "Tipos de comida",
    subtitle:
      "Crea, edita y ordena los tipos que usas al planear o registrar comidas.",
    newType: "Nuevo tipo",
    editTitle: "Editar tipo",
    createTitle: "Nuevo tipo",
    delete: "Eliminar",
    deleteSuccess: "Tipo eliminado",
    deleteError: "No pudimos eliminar el tipo. Intenta de nuevo.",
    reorderHint: "Arrastra para ordenar tus tipos de comida.",
    backToPlanMeal: "Volver a planear comida",
    backToRegisterMeal: "Volver a registrar comida",
  },
  nameLabel: "Nombre",
  namePlaceholder: "Ej. Media mañana",
  save: "Guardar",
  create: "Crear",
  cancel: "Cancelar",
  loading: "Cargando tipos…",
  loadError: "No pudimos cargar los tipos de comida.",
  createSuccess: "Tipo agregado",
  updateSuccess: "Tipo actualizado",
  saveError: "No pudimos guardar el tipo. Intenta de nuevo.",
  duplicateName: "Ya existe un tipo con ese nombre.",
  empty: "Aún no tienes tipos personalizados.",
  reorder: "Reordenar",
  reorderError: "No pudimos guardar el orden. Intenta de nuevo.",
} as const;
